import re
import sys

MYSQL_TO_PG_TYPES = {
    r'\bint\b': 'integer',
    r'\bbigint\b': 'bigint',
    r'\bsmallint\b': 'smallint',
    r'\btinyint\(1\)': 'boolean',
    r'\btinyint\b': 'smallint',
    r'\bdatetime\b': 'timestamp',
    r'\bdouble\b': 'double precision',
    r'\bfloat\b': 'real',
    r'\bjson\b': 'jsonb',
    r'\blongtext\b': 'text',
    r'\bmediumtext\b': 'text',
    r'\btext\b': 'text',
    r'\bdecimal\((\d+),(\d+)\)': r'numeric(\1,\2)'
}

def convert_sql(sql: str) -> str:
    lines = sql.splitlines()
    output = []

    skip_block = False

    for line in lines:
        line = line.strip()

        # Skip MySQL-specific commands
        if re.match(r'^(LOCK TABLES|UNLOCK TABLES|DELIMITER|CREATE TRIGGER|CREATE EVENT)', line, re.I):
            skip_block = True
            continue

        if skip_block:
            if line.endswith(';'):
                skip_block = False
            continue

        # Remove ENGINE, CHARSET
        line = re.sub(r'ENGINE=.*', '', line, flags=re.I)
        line = re.sub(r'DEFAULT CHARSET=.*', '', line, flags=re.I)

        # Replace backticks with double quotes
        line = line.replace('`', '"')

        # AUTO_INCREMENT
        line = re.sub(
            r'\bAUTO_INCREMENT\b',
            'GENERATED BY DEFAULT AS IDENTITY',
            line,
            flags=re.I
        )

        # INSERT IGNORE
        line = re.sub(r'INSERT\s+IGNORE', 'INSERT', line, flags=re.I)

        # Data types
        for mysql_type, pg_type in MYSQL_TO_PG_TYPES.items():
            line = re.sub(mysql_type, pg_type, line, flags=re.I)

        # Remove unsigned
        line = re.sub(r'\bunsigned\b', '', line, flags=re.I)

        # Remove MySQL comments
        if line.startswith('--') or line.startswith('/*'):
            continue

        if line:
            output.append(line)

    return '\n'.join(output)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python mysql_to_pg.py input.sql output.sql")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    with open(input_file, 'r', encoding='utf-8', errors='ignore') as f:
        mysql_sql = f.read()

    postgres_sql = convert_sql(mysql_sql)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(postgres_sql)

    print(f"Converted SQL written to {output_file}")
